-- 코드를 작성해주세요
SELECT DISTINCT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO I
LEFT OUTER JOIN ITEM_TREE T
    ON I.ITEM_ID = T.PARENT_ITEM_ID
        AND RARITY = 'RARE'
        AND T.ITEM_ID IS NOT NULL
INNER JOIN ITEM_INFO II
    ON T.ITEM_ID = II.ITEM_ID
ORDER BY II.ITEM_ID DESC;
