-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
    WHERE BIN(SKILL_CODE) LIKE (SELECT CONCAT('%', REPLACE(BIN(CODE), '0', '_')) FROM SKILLCODES WHERE NAME = 'Python')
        OR BIN(SKILL_CODE) LIKE (SELECT CONCAT('%', REPLACE(BIN(CODE), '0', '_')) FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID;
