-- 코드를 작성해주세요
SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    (B.MAX - A.SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA A
    INNER JOIN (
        SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
        FROM ECOLI_DATA
        GROUP BY YEAR
    ) AS B
    ON YEAR(DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV;